### PR TITLE
AppRouter support className and fix window.microApps not equal to insider microApps variable

### PR DESCRIPTION
**Pull request by coffeedeveloper**
## AppRouter support className
The `AppRouter` component will render an empty div to mount children, but can't add `className` to allow custom style.

## fix window.microApps
`window.microApps` assign to `microApps` variable, [https://github.com/ice-lab/icestark/blob/master/packages/icestark/src/apps.ts#L103](https://github.com/ice-lab/icestark/blob/master/packages/icestark/src/apps.ts#L103)
but `updateAppConfig` function called, `microApps` variable will reassign to new Array and window.microApps will not equal any more. [https://github.com/ice-lab/icestark/blob/master/packages/icestark/src/apps.ts#L160](https://github.com/ice-lab/icestark/blob/master/packages/icestark/src/apps.ts#L160)

### CODE REVIEW

**Comment by wisdomofgod** [comment]
邮件已收到~~

**Review by ClarkXia — APPROVED** [review]
LGTM

**Comment by ClarkXia** [comment]
冲突处理下

**Comment by coffeedeveloper** [comment]
已解决冲突

**Review by ClarkXia — APPROVED** [review]

**Comment by maoxiaoke** [comment]
LGTM

**Review by maoxiaoke — APPROVED** [review]

**Pull request merged**
